version: '3'
services:
        web:
                image: flask_port_v1
                build: .
                ports:
                        - "8056:8080"
                volumes:
                        - persistent_volume:/app/volumes
                restart: unless-stopped
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/T8056_berries/volumes
